name: SysInput CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        zig-version: ['0.14.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Build
        run: zig build

      - name: Run tests
        run: zig build test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SysInput-${{ runner.os }}
          path: zig-out/bin/SysInput.exe
          if-no-files-found: error
